### PR TITLE
Role patch preparing for Thanos Query API RBAC settings update

### PR DESCRIPTION
**Pull request by raptorsun**
The Thanos Query deployment [will be updated soon](https://github.com/openshift/cluster-monitoring-operator/pull/2136) in Cluster Monitorinng Operator. Its Oauth-proxy guarding the web port before Thanos Query will be swapped to Kube-rbac-proxy. Due to new RBAC settings, the priviledge to access the web port is determined by `get` , `create` and `update` verb on the resource `prometheuses/api`. 
The JIRA task for this change is https://issues.redhat.com/browse/MON-3379
Here is a video explaining this change: https://drive.google.com/file/d/1j-22p6H7MOm7vPpA5HmAjq4EcrX4jrpj/view?usp=drive_link

### CODE REVIEW

**Comment by maskarb** [comment]
@raptorsun thanks for the PR! Do we know what versions of Openshift will receive this new `rbac-proxy`? It's not abundantly clear from the linked issue when this would be released.

I'm testing these changes to ensure they are good to go, but I have no concerns about them.

**Comment by raptorsun** [comment]
> @raptorsun thanks for the PR! Do we know what versions of Openshift will receive this new `rbac-proxy`? It's not abundantly clear from the linked issue when this would be released.
> 
> I'm testing these changes to ensure they are good to go, but I have no concerns about them.

The replacement of Oauth proxy is planned to be delivered in 4.15. We are looking for other services dependant on the Thanos query service and seek solution for a smooth transition :)

**Comment by raptorsun** [comment]
> And just to clarify, this will not be backported to any version prior to 4.15?

There is no plan to backport this proxy replacement at the moment.

**Review by maskarb — APPROVED** [review]
lgtm!

**Pull request merged**
